### ISSUE TITLE
dashboard for editors

### ISSUE THREAD

**Issue by AbeHandler** [TheLens/elections#140]
see what races are running, pick how the candidates names should be displayed, pick their colors ==> dump out a config file that gets passed to the front end. front end reads from the config file and makes the election coverage. 

http://www.aboutmcdonalds.com/content/dam/AboutMcDonalds/Logo/im_loving_it_archers_lockup/images/ml_rm_ilib_tm_2cc_l_e.gif

**Comment by ThomasThoren** [comment]
I'm abstracting as much as possible, but there comes a point where a developer will have to get involved for most races. For the Oct. 24, 2015, race, there are unusual shapes like BESE districts, OPSB districts and the French Quarter Economic Development district. Unless we made all potential shapes up front, this sort of work will always be required for future elections.

I'll close this, but continue to abstract and pull information into as few config files as possible.
