### ISSUE TITLE
should be able to handle responsive iframe

### ISSUE THREAD

**Issue by AbeHandler** [TheLens/elections#149]

**Comment by myersnews** [comment]
This is probably going to be an issue again this year. It's possible they don't care, but during the election I'll check their mobile site and see how our app looks on it.

**Comment by ThomasThoren** [comment]
We're able to do this now with pym.js if they want it to be truly responsive. Otherwise, it will fit the page on load and be static afterward. I'm still talking with their web editor to sort everything out.

**Comment by myersnews** [comment]
Last time, they saw the ipad view because of the size of the iframe. That’s fine, but we need to make sure that view looks good. I’ll do it.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
