### ISSUE TITLE
Solution to tooltips on mobile

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#170]
We've discussed this before, but we should actually do something about it. Tooltips are really hard to use on such a tiny, imprecise screen. INN suggested we have an option to display the results in a table or in charts. We could even add the option to let people search for their precinct by either accessing their current location or having them enter their address. Kaeti did this while at MinnPost: http://www.minnpost.com/results#dashboard
There are non-server ways of doing this, such as the recently released Wherewolf.js by WNYC's Noah Veltman.

**Comment by myersnews** [comment]
I agree that it's a problem. But yeah, we can't deal with it now.

**Comment by ThomasThoren** [comment]
See #324 for a way to handle this.
