### ISSUE TITLE
Don't use same color schemes for similar races

### ISSUE THREAD

**Issue by AbeHandler** [TheLens/elections#182]
Steve:  we used same colors for 2 judge races?
 me:  ya
 Steve:  let's not do that next time.
minor issue.

**Comment by ThomasThoren** [comment]
I'm using red/orange/yellow/brown for any Republican candidates and blue/teal/purple for Democrats. Any extra candidates, or third party candidates, use green/pink/whatever else is left. This means some similar races use similar color schemes, but I think it's a good tradeoff so there's some level of consistency in what each color represents.
