### ISSUE TITLE
change twitter/FB language

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#199]
Now:
I'm watching live election results of Louisiana and New Orleans.

Change to:
I'm watching live election results for Louisiana governor & other races @TheLensNOLA. 

FB text is wrong -- says it's for Dec. 6, 2014. I don't know where that text comes from -- is it autofilled or did you do it?

**Comment by ThomasThoren** [comment]
I write the social media sample text into the page's <head> section for Facebook and Twitter. The Dec. 6 language is probably because I copied last election's social media language and didn't alter it.
