### ISSUE TITLE
check transparency of parish colors when all precincts returning

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#202]
earlier today, it said all precincts were reporting but the colors weren't solid, or whatever you call it when it's not somewhat transparent. Now that the app says 0 precincts reporting I can't check it.

**Comment by ThomasThoren** [comment]
This is probably because of the test data. I'll check on it to be sure.

**Comment by ThomasThoren** [comment]
The test data was to blame. The displayed "X precincts reporting" for each parish doesn't correspond to the percent of precincts reporting in the test data. Each is generated randomly, independent from each other.
