### ISSUE TITLE
FQ precincts

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#203]
Re: the precinct that is somewhat out of the quarter, did you check to see if the entire precinct votes?

Even if it doesn't, I don't think we need to change the map.

**Comment by ThomasThoren** [comment]
The French Quarter Economic Development District roughly follows the shape shown here: http://www.fqmd.org/maps/

The precincts you see for the French Quarter sales tax have been clipped according to that shape. Several of them extend outside of the French Quarter, but those residents do not vote for the sales tax. I'm still waiting to hear exactly how that works logistically.

On a related note, there should be eight precincts shown. I still need to re-cut the district. It actually extends one property beyond Rampart (toward the lake) and one property beyond Esplanade (downriver). This is why you only see six precincts right now.

**Comment by myersnews** [comment]
OK.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
