### ISSUE TITLE
change phone nav

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#204]
Can we change the races to a single dropdown or two dropdowns (one for ballot propositions and one for other races)? Prefer the first one. 
Here's what it looks like on the phone. Not only is the list really long, but the text on the ballot propositions stacks with just one word on a line.

![img_8190](https://cloud.githubusercontent.com/assets/413882/10681147/eaad50b2-78eb-11e5-8739-3601e60a95d4.PNG)

**Comment by ThomasThoren** [comment]
What do you think about this?

![screen shot 2015-10-23 at 11 18 00 am](https://cloud.githubusercontent.com/assets/5692185/10698666/c9a2dd4c-7977-11e5-9d4f-9ea97b076c14.png)

**Comment by myersnews** [comment]
Good. How about we default to minimizing the races on phone view only? That way the results table is higher.
