### ISSUE TITLE
move map view options off map on phone?

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#205]
given how small the map area is, it would be better if this nav box didn't sit on the map. not a high priority.

**Comment by ThomasThoren** [comment]
Not sure if you filed this before or after I made a change to the detail selector. Here's what it looks like for the mobile view. You can click to show or hide the radio buttons.

The smaller Lens logo is meant to free up some space too.

![screen shot 2015-10-22 at 11 35 36 pm](https://cloud.githubusercontent.com/assets/5692185/10684677/b6d78288-7915-11e5-98a1-939a50e8643c.png)

**Comment by myersnews** [comment]
Yeah, that should work. I think that's as much as we can do.
