### ISSUE TITLE
Ballot language is confusing

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#206]
The headings aren't descriptive enough. I will write new ones.

Wonder if we should also put the "learn about this issue" next to the headings on the nav. Though if we do, we'll have to pull it off on mobile.

**Comment by myersnews** [comment]
Can we add a subhed to each of these, in the header area of the results table (below the heading and above "learn about this issue"? It would say, in order:

Create a new transportation projects fund and restructure the rainy day fund

Allow the state treasurer to invest in public funds in the state infrastructure bank for transportation projects

Change guidelines for legislation in a fiscal session

Allow local governments to tax property owned by local or state governments outside Louisiana

Add .2495% to the sales tax in the French Quarter

**Comment by myersnews** [comment]
Revised guidance. First line is nav heading, second line is the subhed in results box.

1
Rainy day fund and transportation fund
Create a new transportation projects fund and restructure the rainy day fund

2
State Transportation Infrastructure Bank
Allow the state treasurer to invest in public funds in the state infrastructure bank for transportation projects

3
Legislative fiscal session
Change guidelines for legislation in a fiscal session

4
Tax property owned by other states
Allow local governments to tax property owned by local or state governments outside Louisiana

5
(current heading is correct)
Add .2495% to the sales tax in the French Quarter

**Comment by ThomasThoren** [comment]
Confused by what you mean for the layout.

This?
![screen shot 2015-10-23 at 12 54 45 pm](https://cloud.githubusercontent.com/assets/5692185/10700737/6c1205be-7985-11e5-8de5-f5e8993a3d7f.png)

Or this?
![screen shot 2015-10-23 at 12 55 24 pm](https://cloud.githubusercontent.com/assets/5692185/10700738/6d60222a-7985-11e5-8aeb-39a4160c73f3.png)

**Comment by myersnews** [comment]
First one.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by myersnews** [comment]
Typo in my instructions for #2 subhed:
invest in public funds - delete the "in"

and cut the ending "for transportation projects" - pushes down one more line.

Can you add a horizontal rule below the heading of the results box or make sure the font sizes for results box heading and subhed are different enough?

**Comment by ThomasThoren** [comment]
Here's the current format:

![screen shot 2015-10-23 at 1 20 20 pm](https://cloud.githubusercontent.com/assets/5692185/10701381/d9ac2fa2-7988-11e5-8710-9055638bc37e.png)
