### ISSUE TITLE
change map nav language

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#207]
Heading now says: Select Details view
Change to: Select view

Change the color legend to:
Light shades indicate incomplete results

Think that will work? The presumption then is that a dark shade is complete. I don't want to use that language though because "dark shade" could indicate a dark color.

**Comment by ThomasThoren** [comment]
Take a look now and see if you like it. I'm comfortable with the shorter description if you are.

**Comment by myersnews** [comment]
Looks good.
