### ISSUE TITLE
map view-too wide?

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#208]
On wide screens, even my 13 inch laptop, we get a wide map with nothing in it. This isn't a dealbreaker, but I don't think we're using the space effectively.

Maybe we make the map taller and zoom in one more level on desktop. I think you would have to make it about 270 px taller in order to do this.

**Comment by ThomasThoren** [comment]
I increase the height for most page widths, but the "large" width (full width on a 13-inch laptop) doesn't have enough height to be able to fit another zoom level. Users will have to scroll up and down to take in all of the state, which we don't want.

I added an extra-large width style that increases the height enough to fit that extra zoom level. This works well on a full desktop monitor.

Play around with the new widths/heights when you get a chance and let me know what you think.
