### ISSUE TITLE
iPad (could be iphone too) map nav hard to work

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#211]
The map is running slow now so I'm not exactly sure what's going on, but I think the touch area for the map area is too small. I keep hitting and it doesn't work, and then suddenly it does.

**Comment by myersnews** [comment]
I think it's fine on the iphone. Perhaps a bit tough to hit the right spot as well.

**Comment by ThomasThoren** [comment]
Things should be speedier all around now. The targets are larger too, so give it a try and see if it works any better for you.

**Comment by myersnews** [comment]
Yeah, it's better.
