### ISSUE TITLE
Add St. Bernard precincts

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#212]

**Comment by ThomasThoren** [comment]
Note to myself:

In `_kingfish.py`, need to change `get_json` to accept a list of parishes for the 'details' parameter instead of a string for a single parish.

**Comment by ThomasThoren** [comment]
Sent these records requests yesterday.

**Comment by ThomasThoren** [comment]
Currently have these parishes, and have confirmed they are up to date:

* Orleans
* Jefferson

Have these parishes, but have not yet confirmed they are up to date:

* Ascension
* East Baton Rouge
* Plaquemines
* St. Charles
* St. James
* St. John the Baptist
* Livingston

Waiting for records for these parishes:

* Caddo
* St. Tammany

The second group includes a lot of parishes we didn't talk about including, but I found most of them online in a ready-to-go format. If they are up to date, I'd say we might as well include them. We could potentially show all precincts along the river starting with Baton Rouge.

**Comment by ThomasThoren** [comment]
Waiting to get St. Bernard and St. Tammany records. St. Bernard isn't a must, but I asked for their precincts just to see if it isn't too much extra trouble since WWL asked for their parish president race.

**Comment by ThomasThoren** [comment]
We've received St. Tammany's precincts. Still waiting to hear from St. Bernard.

**Comment by ThomasThoren** [comment]
St. Tammany added in 8e9a211.

**Comment by ThomasThoren** [comment]
Just got Lafayette Parish precincts. The file looks like it's good quality, so it shouldn't take long to add.

**Comment by myersnews** [comment]
OK, but put this after the bug fixing on the front end. Bugs before
enhancements!

--
Steve Myers
Special projects editor
The Lens <http://thelensnola.org/>, New Orleans' first independent,
nonprofit news site
504-298-9750
@myersnews <http://twitter.com/myersnews>

**Comment by ThomasThoren** [comment]
St. Bernard doesn't have a GIS file with new precincts on hand. It's possible they could get a file from their consultant, but not by Saturday. St. Bernard was always WWL's idea anyway, so I'm ditching this idea.
