### ISSUE TITLE
map nav not changing when you change races

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#215]
If you choose a race and then select New Orleans, and then select another race, it zoom out to statewide but the button says it's still the New Orleans view. It should stay on the New Orleans view (on whatever view you've selected) when you change races.

**Comment by ThomasThoren** [comment]
Nevermind, still seeing bugs with this.

**Comment by ThomasThoren** [comment]
Should be working now. Let me know if you see any issues.

**Comment by myersnews** [comment]
Looks good.
