### ISSUE TITLE
desktop view: top nav too tall

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#216]
I don't think it was like this before, but I can't be sure. The top nav is so tall on my 13 inch screen that you have to scroll up to change race. You can't see most of the map when the nav is down.

Easiest solution is to hide all the races below treasurer (which is on the same line as the french quarter tax). Use the same convention as for showing additional candidates, with a line that says "Show all races"

And if you do that, you can remove the hiding for BESE races.

Another option (probably not a good one) is to minimize the race box after one is selected. Forces people to keep opening it though to browse around. Not what we want.

**Comment by ThomasThoren** [comment]
Decreased height slightly. Probably the best I'll be able to do before tonight.

**Comment by ThomasThoren** [comment]
Is this still a problem for you with the new app?

**Comment by myersnews** [comment]
It’s OK on my 13 inch. You have to scroll down to see the entire state but once you do, you can see the whole state and the top nav without scrolling.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews
