### ISSUE TITLE
Decrease map height on mobile, at least for phones with narrow screens. Scrolling is difficult with current height.

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#223]
I increased it close to election day so we could accommodate an additional zoom level. That might have worked for the newer, larger phones, but for narrow screens (iPhone 4s for example), this results in a lot of wasted map area above and below Louisiana since the map can't zoom in that extra level.

That also made it difficult for users to scroll back up the page to see the table. Grabbing the map makes it pan, so users have to grab the the non-map part of the page. For these narrow phones, that space is only a narrow strip around the map's edges. If the map height was decreased on these narrow phones (or all phones), then there would be more space on the screen above the map that could be grabbed for scrolling.

**Comment by ThomasThoren** [comment]
Should be fixed now, but I'm waiting for Marta's feedback (she pointed out this problem).

**Comment by myersnews** [comment]
we could just buy her a new phone.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I'd rather we take her phone away altogether and force her to use a laptop. Then we'll do the same for all of our readers too.
