### ISSUE TITLE
Add Jefferson and Algiers levee millage races

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#226]
We're showing the Orleans runoff for OPSB District 1. Are we also going to show the runoff races in Jefferson, St. Tammany, and others now that we'll have their precincts? This would complicate the nav bar.

Here's what I have compiled so far for those runoffs:

__Caddo__
State Senator -- 38th Senatorial District
State Representative -- 7th Representative District
District Attorney -- 1st Judicial District Court
Parish Commission Member -- District 3
Parish Commission Member -- District 8

__St. Tammany__
Sheriff
Clerk of Court
Council Member -- District 7
Council Member -- District 14
Justice(s) of the Peace -- Justice of the Peace Ward 8

__East Baton Rouge__
State Representative -- 29th Representative District
State Representative -- 63rd Representative District
State Representative -- 66th Representative District
State Representative -- 69th Representative District For Regular and Unexpired Term

__Jefferson__
State Senator -- 7th Senatorial District

**Comment by ThomasThoren** [comment]
Here's an updated list from a new XML file on the Secretary of State's server. I didn't realize there would be new ballot measures for the general election.

## Caddo

__Candidates__
State Senator -- 38th Senatorial District
State Representative -- 7th Representative District
District Attorney -- 1st Judicial District Court
Parish Commission Member -- District 3
Parish Commission Member -- District 8

## East Baton Rouge
__Candidates__
State Representative -- 29th Representative District
State Representative -- 63rd Representative District
State Representative -- 66th Representative District
State Representative -- 69th Representative District For Regular and Unexpired Term

__Ballot measures__
PW Plan of Government -- Include Cities of BR, Zachary, Baker, Central in Budget
Fire Protection District No. 1 -- $32 Service Charge - MC - 10 Yrs.
Brownsfield Fire Protection Dist. No. 3 -- 10 Mills - MC - 10 Yrs
City of Baker -- 5% Hotel Tax - CC - Perp" ParishName="East Baton Rouge
Southern Heights Nbrhd. Crime Prev. &amp; Imp. Dist. -- $100 Parcel Fee - BOC - 10 Yrs.
Shenandoah Estates Crime Prev. &amp; Imp. Dist. -- $50 Parcel Fee - BOC - 8 Yrs.
Woodlawn Estates Crime Prev. &amp; Imp. Dist. -- $150 Parcel Fee - BOC - 10 Yrs.
Fire Protection District 6 -- 5 Mills - BOC - 9 Yrs.
Forest Heights Pk. Crim. Prev. &amp; Imp. Dist. -- $120 Parcel Fee - BOC - 10 Yrs.
Riverbend Crime Prev. and Imp. Dist. -- $150 Parcel Fee - BOC - 15 Yrs.

## Jefferson
__Candidates__
State Senator -- 7th Senatorial District

__Ballot measures__
West Jefferson Levee District -- 5.50 Mills - BOC - 30 Yrs.

## Orleans
__Candidates__
Member of School Board -- District 1

__Ballot measures__
Broadmoor Neighborhood Improvement District -- $100 Parcel Fee - CC - 5 Yrs.
Algiers Levee District -- 6.35 Mills - BOC - 30 Yrs.

## St. Tammany

__Candidates__
Sheriff
Clerk of Court
Council Member -- District 7
Council Member -- District 14
Justice(s) of the Peace -- Justice of the Peace Ward 8

__Ballot measures__
PW HRC Amend. Prop. No. 1 -- Sec. 1-06, Art. I - PC
PW HRC Amend. Prop. No. 2 -- Sec. 1-07, Art. I - PC
PW HRC Amend. Prop. No. 3 -- Sec. 2-07, Art. II - PC
PW HRC Amend. Prop. No. 4 -- Sec. 2-14, Art. II - PC
PW HRC Amend. Prop. No. 5 -- Sec. 4-03, Art. IV - PC
PW HRC Amend. Prop. No. 6 -- Sec. 3-09, Art. III - PC
PW HRC Amend. Prop. No. 7 -- Sec. 4-02, Art. IV - PC
PW HRC Amend. Prop. No. 8 -- Sec. 4-04 through 4-12, Art. IV - PC
PW HRC Amend. Prop. No. 9 -- Sec. 5-02, Art. V - PC
Road Lighting District No. 9 -- $50 Serv. Chg. - PC - 10 Yrs.
City of Covington -- 1% S&amp;U - CC - 18 Yrs
Village of Folsom -- .5% S&amp;U - M&amp;BOA - 10 Yrs.
Fire Protection District No. 7 -- 5.21 Mills - BOC - 10 Yrs.
Gravity Drainage District No. 5 -- .50 Mills - BOC - 10 Yrs.
Recreation District No. 7 -- 3.98 Mills - BOC - 10 Yrs.
Fire Protection District No. 11 -- 10 Mills - BOC - 10 Yrs

**Comment by ThomasThoren** [comment]
The final race list:

Governor
Lieutenant governor
Attorney general
St. Bernard Parish President (if we get the precincts)
St. Tammany Sheriff
St. Tammany Clerk of Court

OPSB district 1
BESE districts 4 and 6

All House races (districts 7, 12, 36, 38)
All Senate races (districts 29, 32, 34, 40, 45, 51, 53, 63, 66, 69, 72, 99, 100, 103)

__New (recommended by Bob)__
West Jefferson Levee District -- 5.50 Mills - BOC - 30 Yrs. (Jefferson Parish)
Algiers Levee District -- 6.35 Mills - BOC - 30 Yrs. (Orleans Parish)

**Comment by myersnews** [comment]
I’m pretty sure those levee districts are noncontroversial, and they add another type of race. Beatty recommended against them. Check with Beatty to make sure.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Bob is doing more research into them. The Jefferson millage doubles their current rate, so that's of interest. Algiers is a millage renewal, though it will also increase the overall amount of money for the levee district since property values are higher now.

**Comment by ThomasThoren** [comment]
Leaning towards not adding the millages, but I'll leave this open in case I have the time. Other than that, this is the final list (removed St. Bernard Parish President):

Governor
Lieutenant governor
Attorney general
St. Tammany Sheriff
St. Tammany Clerk of Court

OPSB district 1
BESE districts 4 and 6

All House races (districts 7, 12, 36, 38)
All Senate races (districts 29, 32, 34, 40, 45, 51, 53, 63, 66, 69, 72, 99, 100, 103)

**Comment by ThomasThoren** [comment]
Not going to show either levee measure.
