### ISSUE TITLE
For map's view options, change to statewide radio button and parish-level dropdown menu

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#232]

**Comment by ThomasThoren** [comment]
What do you think about this design, @myersnews? You can either click on "Statewide" or select from the parishes dropdown.

![screen shot 2015-11-19 at 12 39 21 pm](https://cloud.githubusercontent.com/assets/5692185/11280322/143d2026-8ebb-11e5-8992-3cd99809844b.png)

![screen shot 2015-11-19 at 12 37 43 pm](https://cloud.githubusercontent.com/assets/5692185/11280323/143fd082-8ebb-11e5-985b-57e87f0ffc8f.png)

**Comment by myersnews** [comment]
This will work, but what about “Local”? They’ll get precinct-level results but most people don’t know what precincts are anyway.

I think you can remove the > too.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Like this?

![screen shot 2015-11-19 at 12 53 11 pm](https://cloud.githubusercontent.com/assets/5692185/11280682/a996eb92-8ebc-11e5-89d6-f37c3f99b112.png)

I don't think there's enough of a visual cue that you can click on those options. I removed the HTML radio buttons because I didn't want to hack around their built-in functions, but I could add a custom radio icon to accomplish the same thing visually, like this:

![screen shot 2015-11-19 at 12 57 38 pm](https://cloud.githubusercontent.com/assets/5692185/11280776/22353356-8ebd-11e5-9cbd-c5330c81495a.png)

**Comment by myersnews** [comment]
ok, good point about making people know they’re clickable. a checkbox implies multiple selections, which isn’t what we want. what if you make statewide and local look like buttons, and highlight them if they’re pressed? i don’t exactly know how the local button would work - if the dropdown is part of that button or next to it.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
You're right: Check marks aren't the right icons for selecting a single option. Here's a similar approach that could work. It could also highlight the selected option, like how the nav bar works.
 
![screen shot 2015-11-19 at 1 07 32 pm](https://cloud.githubusercontent.com/assets/5692185/11281082/8b5298c8-8ebe-11e5-920c-e36b90300cd9.png)

**Comment by ThomasThoren** [comment]
With a less noticeable circle icon, to give the selected option more emphasis: 

![screen shot 2015-11-19 at 1 10 50 pm](https://cloud.githubusercontent.com/assets/5692185/11281182/05cb0b1c-8ebf-11e5-8e1e-fad0a07bcf3d.png)

**Comment by myersnews** [comment]
Somewhat ambivalent about mixing radio buttons and checkboxes but give it a shot. It’s better than what we have now and it may work fine.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Here we go. I didn't notice this filled-in radio button icon earlier:

![screen shot 2015-11-19 at 1 15 06 pm](https://cloud.githubusercontent.com/assets/5692185/11281293/98fc85c8-8ebf-11e5-945b-f8b726bd2f2e.png)

**Comment by myersnews** [comment]
that’s better. that will work.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Changed in f8bb9ae8eda4e13b8cc268b1d3f4a1c81446740d.
