### ISSUE TITLE
Provide increased precision for when percent of precincts reporting approaches 100 percent?

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#233]
We round to the nearest percent for most of the night, but it might be a good idea to be more precise once the percentage approaches 100 percent. For example, this would be better as 99.7%.

![screen shot 2015-11-09 at 5 31 05 pm](https://cloud.githubusercontent.com/assets/5692185/11049991/eb624934-8707-11e5-9e0e-dc62903b729e.png)

On the other hand, displaying 99.97% for when there are 3944 out of 3945 precincts reporting might be overkill.

**Comment by myersnews** [comment]
Agree on going to tenths. Can you keep it from going to 100% until all have
reported? So even if it would round to 100 you would force it to say 99.9.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Nov 9, 2015, at 5:36 PM, Thomas Thoren <notifications@github.com> wrote:

We round to the nearest percent for most of the night, but it might be a
good idea to be more precise once the percentage approaches 100 percent.
For example, this would be better as 99.7%.

[image: screen shot 2015-11-09 at 5 31 05 pm]
<https://cloud.githubusercontent.com/assets/5692185/11049991/eb624934-8707-11e5-9e0e-dc62903b729e.png>

On the other hand, displaying 99.97% for when there are 3944 out of 3945
precincts reporting might be overkill.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/233>.

**Comment by ThomasThoren** [comment]
Yeah I could have it round down to 99.9 until it is truly 100. Good idea.

Do you think we should display tenths the entire time, or only once the percent gets close to 100?

**Comment by myersnews** [comment]
Liked idea of doing it when it gets close but maybe that's too complicated.
Up to you.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Nov 9, 2015, at 5:46 PM, Thomas Thoren <notifications@github.com> wrote:

Yeah I could have it round down to 99.9 until it is truly 100. Good idea.

Do you think we should display tenths the entire time, or only once the
percent gets close to 100?

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/233#issuecomment-155235499>.
