### ISSUE TITLE
Add final funders list

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#235]
For most-generous donors from Beacon.

Add template for Anne before Saturday morning.

**Comment by myersnews** [comment]
Can you set it up so this doesn't appear on the embed for wwl?

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Nov 10, 2015, at 9:26 AM, Thomas Thoren <notifications@github.com> wrote:

For big donors from Beacon.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/235>.

**Comment by ThomasThoren** [comment]
Yeah. I'll probably make a separate page for them that includes everything except this section. I made two separate pages when we worked with The Nation and that worked out well.

**Comment by myersnews** [comment]
10-4
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
First stab at this in 2f758bb. I'll expand on it once we have the actual list.

**Comment by ThomasThoren** [comment]
Separate URL for WWL's embed: http://elections.thelensnola.org/2015/gubernatorial-general/wwl.html
