### ISSUE TITLE
Caddo and East Baton Rouge results data has some precincts with "sub"-precincts (1A, 1B, etc), but their shapefiles do not

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#238]
For example, the East Baton Rouge shapefile has precinct "1-80." In the Secretary of State's data, that precinct doesn't exist. The Secretary of State data does, however, have two similar precincts: 1-80A and 1-80B, both of which don't exist in East Baton Rouge Parish's records.

This affects a significant portion of East Baton Rouge Parish's precincts and about a dozen precincts in Caddo.

You can see what I'm referring to in the primary results:

__Caddo__
http://staticresults.sos.la.gov/10242015/10242015_09_50499_Precinct.html

__East Baton Rouge__
http://staticresults.sos.la.gov/10242015/10242015_17_50499_Precinct.html

Neither Orleans nor Jefferson have this problem.

I'm waiting to hear back from the Secretary of State's office to learn more about how they name precincts. Hopefully the A/B/C sub-precincts don't have any geographical meaning.

Even if they do, it's possible that the sub-precinct letters exist because the precinct ("1-80" in this example) was split, and therefore the sub-precincts could be merged to form that original precinct. If that is the case, I could map the overall precinct ("1-80") and make its underlying data equal to the sum of the sub-precincts, and change the tooltip's label to something like, "Precincts 1-80A and 1-80B." This would lose a level of detail for some precincts in each parish, but it would still be accurate because we would only be summarizing those details. That's the same thing we are doing by showing parish-level results. (I've already started writing this merging code just in case we need it.)

On the other hand, if those sub-precincts turn out to represent some completely different geographical shape, then I don't know what we'll do. Each parish has given me what they say are their most up-to-date precinct maps, so this shouldn't be the case.

cc @myersnews

**Comment by myersnews** [comment]
Jesus, this is a minefield. Check with the parish supervisor of elections (which should be someone in the clerk of civil court’s office).
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
All right, I have an answer, and it's a good one. Meg Casper at the Secretary of State's office says that the A/B/C/etc. subcategories for a precinct have no effect on that precinct's geographic boundaries.

For example, precincts 80A and 80B both occupy the same shape on a map. This means there used to be a precinct 80 that grew too large and was split into precincts 80A and 80B. Half of the voters in what used to be precinct 80 are now recorded as precinct 80A and the other half are recorded as 80B. Their shapes are still the same.

In this example, there are now two separate books for that precinct. They make the split based on last name, so 80A is for A-L and 80B is for M-Z. Some precincts even have a subprecinct C, which would mean the voters are split three ways, again based on their last names.

I'll continue writing that code I mentioned in my previous comment. Subprecincts will still count as their own precinct for when we show the number of precincts reporting. For the map, we will sum the subprecincts' votes into a single shape, which will then have a note about it including multiple precincts in the tooltip language.

**Comment by ThomasThoren** [comment]
I just spoke with the GIS employee who made this map for East Baton Rouge Parish.

http://ebrgis.maps.arcgis.com/apps/webappviewer/index.html?id=bffcd9c0aeea40f9853993c6dc4956c0

He said he took the same approach of aggregating split precincts into a single precinct. I'm trying to get ahold of Caddo's GIS director to verify that we can do the same for their precincts.

**Comment by myersnews** [comment]
So they have created a sub-precinct based on something other than geography — a portion of people in that area are counted as A and others are B. So yeah, your approach makes sense.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
This should be taken care of for all precincts. I'll leave this open until I'm absolutely sure that everything was converted correctly.
