### ISSUE TITLE
Tighten up Caddo Parish shapefile's precinct boundaries and gaps

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#240]
There are gaps between some precincts that become very apparent after a couple of zoom levels.

**Comment by ThomasThoren** [comment]
Do this if time allows for it. Otherwise, restrict zoom level to hide the gaps.

Either way, call to confirm accuracy of file.

**Comment by ThomasThoren** [comment]
Caddo GIS says they are aware of gaps, but stand by the file's accuracy.

**Comment by myersnews** [comment]
the key question is whether there are any residents in those gaps.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
He said the gaps should only appear due to two precincts not perfectly meeting at road center lines, intersections, interstate exchanges and things like that. I'll look at the precincts laid on top of the Mapbox map to see if that's true.

**Comment by ThomasThoren** [comment]
Limited zoom in e0abdb9.

**Comment by ThomasThoren** [comment]
This isn't an issue anymore now that the zoom level is restricted.
