### ISSUE TITLE
Decide how to load precincts and precinct-level results

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#247]
At present, the app always downloads all precinct shapes and their precinct-level results. It first downloads the necessary files and then downloads the rest asynchronously in the background.

We've talked about somehow waiting to download these files until a user decides to view them in order to cut down on loading time and data usage. After looking at the app in its current state, however, I'm not sure that we need to make any changes.

The current app has an overall size of 1.0 MB (up from 862 kB in the primary election). I was expecting this to be much larger. 1 MB is on the larger side of what I aim for with our apps, but it really isn't that uncommon. For comparison's sake, our home page is about 2.5 MB.

On the one hand, most users will never use all of the precinct views, which means most users will have some amount of wasted data. Knowingly wasting users' data isn't the most elegant solution. This would also require a good amount time spent on development and debugging.

On the other hand, 1.0 MB is a perfectly reasonable size for a web page, so we aren't talking about a huge amount of wasted data. Of that, I'd estimate that no more than 200 kB of that is spent on the precinct files. The benefit of this extra data is that it saves me a lot of time on development and debugging, which can be spent on other tasks.

As for loading times, there really isn't a difference. Almost all of the precinct shapes and data aren't downloaded until the page is fully loaded anyway (asynchronously), so users wouldn't see much of a difference on page load. They would, however, likely see a lag after clicking on a precinct view, when the browser has to then download and load that data before displaying anything.

I'd argue that the downside of forcing all users to download some amount of unnecessary data is worth the time saved on development and subsequent debugging. We could get it even smaller, but its size is already within reason and the app is already fast and functional.

What are your thoughts, @myersnews? The test page is up to date, so you can load it to see how quick the app already is.

**Comment by ThomasThoren** [comment]
After some front-end changes, I have the overall app size down to 894 kB.

**Comment by myersnews** [comment]
I agree with your analysis. I was not able to test it on my phone, however, because when I load the app on my phone the map doesn’t load.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Sounds good.

The map should be working now. I'll open a new ticket if it continues for you.
