### ISSUE TITLE
Map not displaying on some phones

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#251]
![img_8321](https://cloud.githubusercontent.com/assets/5692185/11220838/874c983e-8d27-11e5-97cf-afdda7cfa61d.PNG)

**Comment by ThomasThoren** [comment]
Are you still seeing this, @myersnews ? I still haven't tracked down the problem, partially because I haven't seen this happen yet on my phone or tablet.

**Comment by myersnews** [comment]
the districts are wrapping properly, but the radio buttons cover the map and the map doesn’t appear.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
The radio buttons will go away once I change that style.

The map should be appearing. You have iOS 9 right? Are you using Safari's new ad blocking feature?

**Comment by myersnews** [comment]
i haven’t turned ad blocking on, though I always use private browsing mode on my phone. i just restarted my phone and now the map appears. so, my end.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Still weird that it happened at all, especially since you were using the private mode. Let me know if you see it again.
