### ISSUE TITLE
Last updated time's change animation starts firing rapidly after a certain amount of time and/or data downloaded

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#255]
I can't find a pattern, but it occurs some time after the front end has downloaded at least one new round of race results.

**Comment by ThomasThoren** [comment]
Haven't seen this since the Secretary of State tests on Tuesday.

**Comment by myersnews** [comment]
is this something that we would only see on election night or during the live test?
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I only saw it during the test. I've been simulating it today by uploading new data and the time stamps, so I should've seen something if there was still a problem.
