### ISSUE TITLE
Add Google Consumer Surveys

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#269]
First decide if we are using it and where to put it.

**Comment by ThomasThoren** [comment]
Are we going to use these now that the app will only be on our site?

**Comment by myersnews** [comment]
Maybe for Google and NOLA.com, but no direct traffic.

The problem, though, is that GCS is a little buggy and it sometimes appears when it shouldn’t, like on direct links.

On the one hand it would probably bring in a couple hundred bucks, but it’s also possible we piss off some people who gave us money.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I believe Abe set it up so it always filters on nola.com/Google but not direct traffic. I never change any of those settings. That's how it's supposed to work at least, if I remember correctly.

If we hit our Beacon goal, I say we don't use the surveys. If we don't get the Beacon money, then it might be worth making some people angry in order to recoup at least some of the costs.

**Comment by ThomasThoren** [comment]
Not using GCS.
