### ISSUE TITLE
increase all transparency

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#317]
so base map is more visible.

**Comment by ThomasThoren** [comment]
I've decreased the complete results opacity from 0.8 to 0.6. Take a look and let me know if it should change again in any way.

**Comment by ThomasThoren** [comment]
Partial results not clearly different now, so I'll have to decrease that too.

**Comment by ThomasThoren** [comment]
Partial is now 0.2 and complete is 0.6.

**Comment by myersnews** [comment]
let’s bump complete up to .7
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
Now at 0.2 and 0.7.

**Comment by ThomasThoren** [comment]
Change back to 0.3 and 0.7 for future elections.
