### ISSUE TITLE
Consider adding comments to this and other apps

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#321]
Anne brought it up at one point.

**Comment by myersnews** [comment]
I’d go for a structured conversation for election night, like a live blog. but it would have to be separate so it didn’t date the app itself.
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
That could be interesting. Closing this issue though since that wouldn't be part of this app.
