### ISSUE TITLE
How to handle incomplete/leading results vs. final results

### ISSUE THREAD

**Issue by ThomasThoren** [TheLens/elections#325]
We've done transparent for leading, opaque for final in the past. Some readers have found this confusing because it can look like two different colors/candidates.

Now that we're using D3 and SVG, we could take advantage of patterns such as this. It might be worth revisiting.

![screen shot 2016-03-01 at 12 28 24 pm](https://cloud.githubusercontent.com/assets/5692185/13437304/25da5bca-dfa9-11e5-818e-36ea954c7f5e.png)

**Comment by ThomasThoren** [comment]
I should add that this is only needed if we want to show parish-level results. If we stick with precincts only, then this situation will never come up because precincts are reported all at once. Either a precinct has reported its results or it hasn't.

**Comment by myersnews** [comment]
If we do it, I suggest the same approach NYT used tonight.


--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by ThomasThoren** [comment]
I don't think there's any need to show parish-level results as well. You can get the same idea from seeing precincts inside of the parish boundary lines.

**Comment by myersnews** [comment]
Yep. Parish level results are just an abstraction anyway.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Mar 4, 2016, at 4:52 PM, Thomas Thoren <notifications@github.com> wrote:

I don't think there's any need to show parish-level results as well. You
can get the same idea from seeing precincts inside of the parish boundary
lines.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/325#issuecomment-192508448>.
