### ISSUE TITLE
color R/D button that is highlighted

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#327]
hard to know whether the gray one is the selected one or not.

**Comment by myersnews** [comment]
perhaps i'm a bit confused by the fact that the race that is pressed down has a link underline and the other doesn't.

**Comment by ThomasThoren** [comment]
Currently working on something along these lines:

![screen shot 2016-03-05 at 10 00 14 am](https://cloud.githubusercontent.com/assets/5692185/13548578/1865aae0-e2b9-11e5-8886-b459ca21d53b.png)

**Comment by myersnews** [comment]
good
--
Steve Myers
smyers@thelensnola.org
Special projects editor, The Lens
504-298-9750
@myersnews

**Comment by myersnews** [comment]
and you can sub that for the "republican primary" line which will save us a line on phone view.

**Comment by myersnews** [comment]
the D button there is a pale blue right? and the R will be pale when it's not pressed? that will work well.

**Comment by ThomasThoren** [comment]
Yeah, that's right. It's live now if you want to take a look.

I can't tell if it's the monitor I'm using or what, but the text in the button looks fuzzy to me. It looks sharp on my phone though.
