### ISSUE TITLE
show just top X finishers?

### ISSUE THREAD

**Issue by myersnews** [TheLens/elections#328]
so many people in D race. how do we make easier to read? one option is to just let it shake out; hillary and bernie will be at the top in each one.

**Comment by ThomasThoren** [comment]
Plan is to include all candidates, but hide any who have dropped out by placing them in an expandable menu.

**Comment by myersnews** [comment]
Or just hide everyone after the top x. Don't worry about whether they
dropped pi.

Sent from my iPhone, which may explain typos & brevity. Possibly dictated
to Siri, which would account for gibberish.

On Mar 4, 2016, at 4:47 PM, Thomas Thoren <notifications@github.com> wrote:

Plan is to include all candidates, but hide any who have dropped out by
placing them in an expandable menu.

—
Reply to this email directly or view it on GitHub
<https://github.com/TheLens/elections/issues/328#issuecomment-192506320>.
